 results = ~/mydatalocal/TP_elimination_L/3_processed_data/quantification/

# multiqc search files in the chosen directory and extract informations when files are those generated by kallisto (mapping report)
# and extract only few relevant results for user-friendly view

multiqc -f 3_processed_data/quantification/ \
-o 3_processed_data/quantification//multiqc_report_quantification/